### ISSUE TITLE
4.2 support?

### ISSUE THREAD

**Issue by GammaGames** [WaffleAWT/Godot-4.3-Third-Person-Controller#1]
Seems to work fine, would be nice if it was available from the asset library

**Comment by GammaGames** [comment]
You can't download it from the asset library browser because it has limited version: 
![image](https://github.com/WaffleAWT/Godot-4.1-Third-Person-Controller/assets/7832163/ff316281-4e3d-4ac7-8238-8951d4ad7063)

**Comment by WaffleAWT** [comment]
> You can't download it from the asset library browser because it has limited version: ![image](https://private-user-images.githubusercontent.com/7832163/347952321-ff316281-4e3d-4ac7-8238-8951d4ad7063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MjY1NzcsIm5iZiI6MTcyMDcyNjI3NywicGF0aCI6Ii83ODMyMTYzLzM0Nzk1MjMyMS1mZjMxNjI4MS00ZTNkLTRhYzctODIzOC04OTUxZDRhZDcwNjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTFUMTkzMTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI3MWM1YjlmMWVlOGViNDM3NDQ1NmFjOWMyOTViZjc2NDFjOWY0ZDQ0ZjI2MDdiYzNkNmM3MWFjZDU0MjViNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EDcpUot3RqPN6ghoVxENVGzRVNF14rsGFzAxHvRtjVo)

Ty for pointing that out, I'm pretty new to the asset store, I have requested an update and it will be up for 4.2 once they approve it.

**Comment by TheIronLefty** [comment]
Was fixed by waffleawt a while ago and forgot to close 😄 and also updated to 4.3 in my PR, it would be nice if you could update the godot asset too again after my PR 😁 .

**Comment by WaffleAWT** [comment]
> Was fixed by waffleawt a while ago and forgot to close 😄 and also updated to 4.3 in my PR, it would be nice if you could update the godot asset too again after my PR 😁 .

Just waiting for them to approve it, I'm adding a state machine to it so we can manage different states

**Comment by TheIronLefty** [comment]
> > Was fixed by waffleawt a while ago and forgot to close 😄 and also updated to 4.3 in my PR, it would be nice if you could update the godot asset too again after my PR 😁 .
> 
> Just waiting for them to approve it, I'm adding a state machine to it so we can manage different states

They updated it and i tested it but it seems to be updated weirdly, the project is still 4.1 and has broken GLTF player and leftover fbx animations as well as old filmic tonemapper scene.

**Comment by WaffleAWT** [comment]
> > > Was fixed by waffleawt a while ago and forgot to close 😄 and also updated to 4.3 in my PR, it would be nice if you could update the godot asset too again after my PR 😁 .
> > 
> > 
> > Just waiting for them to approve it, I'm adding a state machine to it so we can manage different states
> 
> They updated it and i tested it but it seems to be updated weirdly, the project is still 4.1 and has broken GLTF player and leftover fbx animations as well as old filmic tonemapper scene.

Idk why that's happening because the way it works is it downloads the project from this repo, so it's supposed to not happen, I submitted a ticket for that because I have no idea why it's happening

**Comment by WaffleAWT** [comment]
> > > Was fixed by waffleawt a while ago and forgot to close 😄 and also updated to 4.3 in my PR, it would be nice if you could update the godot asset too again after my PR 😁 .
> > 
> > 
> > Just waiting for them to approve it, I'm adding a state machine to it so we can manage different states
> 
> They updated it and i tested it but it seems to be updated weirdly, the project is still 4.1 and has broken GLTF player and leftover fbx animations as well as old filmic tonemapper scene.

I have no idea why that's happening because it's supposed to get the download files from this repo, the asset library works by you providing a repo so it should be downloading from this repo, which it does for sure but apparently it's using an old commit maybe! I will see what's wrong with it,

update, the problem was that I had an old commit hash on the asset library, I fixed it it should be up once they confirm the edit.
